### ISSUE TITLE
报错: 不存在类型或命名空间

### ISSUE THREAD

**Issue by ZjzMisaka** [daiisuukee/mahiro_patter#1]
使用vs2022打开工程后报错IKeyboardMouseEvents和Hook不存在, 是否有额外的配置? 
![image](https://github.com/daiisuukee/mahiro_patter/assets/16731853/677828e0-b748-45ed-9869-ec2c75177e36)

工程内存在丢失的图片和pfx文件, 这些文件是不需要的吗? 
![image](https://github.com/daiisuukee/mahiro_patter/assets/16731853/8880c223-0c7a-4747-8b27-c7f964abe0b8)

**Comment by daiisuukee** [comment]
可能是由于你的NuGet程序包中没有添加对应的KeyMouseHook这个依赖包，需要你手动安装一下，为什么没有这个我也不是很清楚，一般来讲应该和Maven差不多可以自动添加吧（）
工程内丢失的文件确实是没有必要的，只是一些测试用的图片和配置（第一次上传小项目有点生疏）

**Comment by ZjzMisaka** [comment]
感谢 这个包重新导入后解决了
